version: '3.8'

services:
  phpfpm:
    build:
      context: ./docker/php
    container_name: "contract-api-backend-phpfpm"
    ports:
      - 2000:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/php/php:/usr/local/etc/php:ro
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - contract-api-backend
    restart: always

  nginx:
    image: nginx:latest
    container_name: "contract-api-backend-nginx"
    ports:
      - '8080:8080'
      - '80:80'
      - '443:443'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - phpfpm
    networks:
      - contract-api-backend
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: "contract-api-backend-postgres"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200 -c log_statement=all
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      POSTGRES_DB: contract-api-backend
      PGDATABASE: contract-api-backend
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "2432:5432"
    volumes:
      - contract-api-backend-postgres:/var/lib/postgresql/data
      - ./data/postgres:/opt/data
    depends_on:
      - nginx
      - phpfpm
    networks:
      - contract-api-backend

  rabbitmq:
    image: "rabbitmq:3.8.2-management"
    container_name: "contract-api-backend-rabbitmq"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    hostname: "rabbitmq.local"
    ports:
      - "25672:15672"
      - "2672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    tty: true
    privileged: true
    volumes:
      - ./storage/rabbitmq/data:/var/lib/rabbitmq/mnesia
      - ./storage/rabbitmq/logs:/var/log/rabbitmq
    depends_on:
      - nginx
      - phpfpm
      - postgres
    networks:
      - contract-api-backend
    restart: always

volumes:
  contract-api-backend-postgres:
    name: contract-api-backend-postgres

networks:
  contract-api-backend:
    driver: bridge
 
